### ISSUE TITLE
请问怎么在项目里面使用的地方再去注册IApiClient

### ISSUE THREAD

**Issue by wangpengzong** [TaoGame/JCWXCore#3]
我的项目里面把正式测试的公众号appid,AppSecret集合在项目里面了，根据角色不同公众号也不同，所以只有在使用的地方才需要分类发放或回复，我看到demo里面已经把IApiClient _client放在了basecontroller中，但是我需要的是在service的方法里面使用，请问有什么解决方案

**Comment by JamesYing** [comment]
你可以把IApiClient在Service的构造函数中注入
